
import { jsPDF } from "jspdf";
import { AnalysisResult, UploadedFile } from "../types";

export const generateForensicReport = async (result: AnalysisResult, files: UploadedFile[], caseId: string, vin: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header Background
  doc.setFillColor(2, 6, 23); 
  doc.rect(0, 0, pageWidth, 50, 'F');
  
  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text("AUTOEYE ELITE FORENSIC AUDIT", margin, 30);
  
  doc.setFontSize(10);
  doc.setTextColor(99, 102, 241);
  doc.text(`AUDIT ID: ${caseId} | VIN: ${vin || 'UNIDENTIFIED'}`, margin, 40);

  y = 70;
  doc.setTextColor(0, 0, 0);
  
  // Executive Summary Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE VERDICT", margin, y);
  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const summaryLines = doc.splitTextToSize(result.executiveSummary, pageWidth - 2 * margin);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 6 + 10;

  // Metrics Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, pageWidth - 2 * margin, 12, 'F');
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("METRIC", margin + 5, y + 8);
  doc.text("VALUE", margin + 100, y + 8);
  y += 20;

  // Metrics Rows
  const metrics = [
    ["Condition Score", `${Math.round(result.conditionScore * 100)}/100`],
    ["Audit Confidence", `${result.blind_trust_score}%`],
    ["Estimated Liability", `$${result.financials.grandTotal.toLocaleString()}`],
    ["Repair Timeline", `${result.financials.repairDurationDays} Business Days`],
    ["Compliance Tier", result.processing_meta.precision_tier]
  ];

  metrics.forEach(m => {
    doc.setFont("helvetica", "normal");
    doc.text(m[0], margin + 5, y);
    doc.setFont("helvetica", "bold");
    doc.text(m[1], margin + 100, y);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y + 4, pageWidth - margin, y + 4);
    y += 10;
  });

  y += 10;

  // Anomalies Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("CONSOLIDATED ANOMALIES", margin, y);
  y += 12;

  result.consolidatedIssues.forEach((issue, idx) => {
    if (y > 250) {
      doc.addPage();
      y = 30;
    }
    
    doc.setFillColor(idx % 2 === 0 ? 255 : 249, idx % 2 === 0 ? 255 : 250, idx % 2 === 0 ? 255 : 251);
    doc.rect(margin, y - 5, pageWidth - 2 * margin, 20, 'F');
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`${issue.part.toUpperCase()}`, margin + 5, y);
    doc.setFont("helvetica", "normal");
    doc.text(`${issue.issueType} | Severity: ${issue.severity}`, margin + 5, y + 6);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(`$${issue.consolidated_cost.toLocaleString()}`, pageWidth - margin - 25, y + 3);
    doc.setTextColor(0, 0, 0);
    y += 20;
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`Page ${i} of ${pageCount} | Generated by AutoEye Elite Neural Core | Compliance Signature: ${result.processing_meta.forensic_signature.substring(0, 12)}`, pageWidth / 2, 285, { align: "center" });
  }

  doc.save(`AutoEye_Forensic_Report_${caseId}.pdf`);
};
