import { jsPDF } from "jspdf";
import { AnalysisResult, UploadedFile, CaseDetails } from "../types";

export const generateForensicReport = async (
  result: AnalysisResult, 
  files: UploadedFile[], 
  caseId: string, 
  vin: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let yPos = 20;

  // --- HELPER: ADD IMAGE ---
  const addImageToDoc = async (url: string, x: number, y: number, w: number, h: number) => {
    try {
      if (url.startsWith('blob:')) {
        const response = await fetch(url);
        const blob = await response.blob();
        const base64 = await new Promise<string>((resolve) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as string);
          reader.readAsDataURL(blob);
        });
        doc.addImage(base64, 'JPEG', x, y, w, h);
      } else {
        doc.addImage(url, 'JPEG', x, y, w, h);
      }
    } catch (e) {
      console.warn("Could not add image to PDF", e);
      doc.setFillColor(240, 240, 240);
      doc.rect(x, y, w, h, 'F');
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text("Image Unavailable", x + w/2, y + h/2, { align: 'center' });
    }
  };

  // --- PAGE 1: COVER SHEET ---
  
  // Header
  doc.setFillColor(15, 23, 42); // Slate 900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text("AutoEye AI", margin, 20);
  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text("ENTERPRISE FORENSICS UNIT", margin, 28);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`CASE ID: ${caseId}`, pageWidth - margin, 20, { align: 'right' });
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, pageWidth - margin, 28, { align: 'right' });

  yPos = 60;

  // Condition Grade Badge
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 40, 3, 3, 'FD');
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("CONDITION SCORE", margin + 10, yPos + 12);
  
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  const scoreColor = result.conditionScore > 80 ? [16, 185, 129] : result.conditionScore > 50 ? [245, 158, 11] : [239, 68, 68];
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text((result.conditionScore / 10).toFixed(1), margin + 10, yPos + 28);
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("/ 10.0", margin + 35, yPos + 28);

  // VIN Box
  doc.setFillColor(241, 245, 249);
  doc.rect(pageWidth - margin - 80, yPos + 8, 70, 24, 'F');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text("VIN / ASSET ID", pageWidth - margin - 75, yPos + 16);
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(vin || "UNKNOWN", pageWidth - margin - 75, yPos + 26);

  yPos += 55;

  // Financial Summary
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Financial Impact Analysis", margin, yPos);
  
  yPos += 10;
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 15;

  const finData = [
    ["Total Estimate", `$${result.financials.grandTotal.toLocaleString()}`],
    ["Parts Cost", `$${result.financials.totalPartsCost.toLocaleString()}`],
    ["Labor Cost", `$${result.financials.totalLaborCost.toLocaleString()}`],
    ["Est. Duration", `${result.financials.repairDurationDays} Days`],
    ["Total Defects", `${result.detectedIssues.length} Issues`]
  ];

  finData.forEach(([label, value]) => {
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(label, margin, yPos);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(value, margin + 50, yPos);
    yPos += 10;
  });

  // Footer Page 1
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by AutoEye AI v3.0.0 | ISO/IEC 27001 Compliant Processing", pageWidth / 2, 280, { align: 'center' });

  // --- PAGE 2+: ITEMIZED EVIDENCE ---
  doc.addPage();
  yPos = 20;
  
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Detected Anomalies & Evidence", margin, yPos);
  yPos += 15;

  for (let i = 0; i < result.detectedIssues.length; i++) {
    const issue = result.detectedIssues[i];
    
    // Check page break
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    // Container
    doc.setDrawColor(226, 232, 240);
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(margin, yPos, pageWidth - (margin * 2), 50, 2, 2, 'FD');

    // Title & Severity
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text(`${i + 1}. ${issue.part} - ${issue.issueType}`, margin + 5, yPos + 10);
    
    // Severity Badge
    doc.setFontSize(8);
    const sevColor = issue.severity === 'Critical' ? [239, 68, 68] : issue.severity === 'Severe' ? [249, 115, 22] : [16, 185, 129];
    doc.setTextColor(sevColor[0], sevColor[1], sevColor[2]);
    doc.text(issue.severity.toUpperCase(), pageWidth - margin - 30, yPos + 10, { align: 'right' });

    // Details
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);
    doc.text(`Repair: ${issue.repair_suggestion?.method || 'N/A'}`, margin + 5, yPos + 20);
    doc.text(`Cost: $${issue.repair_suggestion?.estimated_cost || 0}`, margin + 5, yPos + 26);
    
    // Technicals
    let techStr = "";
    if (issue.attributes?.length_mm) techStr += `L: ${issue.attributes.length_mm}mm  `;
    if (issue.attributes?.depth_mm) techStr += `D: ${issue.attributes.depth_mm}mm  `;
    doc.text(techStr, margin + 5, yPos + 32);

    // Image Thumbnail
    if (typeof issue.sourceFileIndex === 'number' && files[issue.sourceFileIndex]) {
        await addImageToDoc(files[issue.sourceFileIndex].previewUrl, pageWidth - margin - 45, yPos + 5, 40, 40);
    }

    yPos += 60;
  }

  // Final Save
  doc.save(`${caseId}_Forensic_Report.pdf`);
};